version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=
      - PORT=8080
      - ENV=production
      - SECRET_KEY=
